### ISSUE TITLE
Rainbow doesn't respect nodes without "data-language"

### ISSUE THREAD

**Issue by nijikokun** [ccampbell/rainbow#104] opened 2013-01-19 01:24 UTC
It chooses all pre and code elements even if they are already highlighted and re-highlights or escapes the previously highlighted html.

I have a commit in line to fix this.

**Comment by ccampbell** [comment] 2016-07-03 00:04
Going to close this out since this is working as intended

**Closed by ccampbell** 2016-07-03 00:04 UTC
